### ISSUE TITLE
Glass Shield crash

### ISSUE THREAD

**Issue by Aeron216** [NyanMC/TrinkPlus#1]
Crashed as soon as I equipped a Glass Shield. Now I've been completely locked out of the world since it will repeatedly crash.

TrinkPlus 1.0.0
Trinkets and Baubles 0.31.4
Forge 2860

Crashlog:

https://gist.github.com/Aeron216/88f6746892d69d2f6f2ebd0164490020

Modlist:

https://gist.github.com/Aeron216/93b07b76c647f30a1407ddbb799ee370

**Comment by NyanMC** [comment]
this is an error on trinkets' end, as they changed something in trinkets which broke it. either mod can fix it, so i may fix it in a patch soon (as this reminded me of it).

**Comment by NyanMC** [comment]
should be resolved in 1.0.1 once curseforge approves it (it may take a bit), reopen this issue if the problem persists
