### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Kasia0314** [NyanMC/TrinkPlus#2]
[crash-2023-02-20_14.03.41-client.txt](https://github.com/NyanMC/TrinkPlus/files/10784635/crash-2023-02-20_14.03.41-client.txt)
[debug.log](https://github.com/NyanMC/TrinkPlus/files/10784636/debug.log)
[latest.log](https://github.com/NyanMC/TrinkPlus/files/10784637/latest.log)

**Comment by NyanMC** [comment]
most likely caused by using trinkets 0.32 with trinkplus 1.2.0, should be fixed in trinkplus 2.0.0
